datastore:
  build: .
  volumes:
    - /srv/data:/data
sabnzbd:
  image: funkypenguin/sabnzbd
  volumes:
    - sabnzbd:/config
  volumes_from:
    - datastore
  ports:
    - 8080:8080
  links:
    - plex
couchpotato:
  image: funkypenguin/couchpotato
  volumes:
    - couchpotato:/config
  volumes_from:
    - datastore
  ports:
    - 5050:5050
  links:
    - sabnzbd
    - plex
plex:
  image: funkypenguin/plex
  volumes:
    - plex:/config
  volumes_from:
    - datastore
  ports:
    - 32400:32400
nzbdrone:
  image: funkypenguin/nzbdrone
  volumes:
    - nzbdrone:/config
  volumes_from:
    - datastore
  ports:
    - 8989:8989
  links:
    - sabnzbd
    - plex
